name: Update builds
on:
  workflow_dispatch:
    inputs:
      otp-ref-name:
        required: true
      otp-ref:
        required: true
      arch:
        required: true
jobs:
  update_builds:
    name: "Update builds/"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      OTP_REF_NAME: "${{ inputs.otp-ref-name }}"
      OTP_REF: "${{ inputs.otp-ref }}"
      TGZ: "${{ inputs.otp-ref-name }}-macos-${{ inputs.arch }}.tar.gz"
      BUILDS_TXT: "builds/macos-${{ inputs.arch }}.txt"
    steps:
      - uses: actions/checkout@v4

      - name: "Add ${{ env.OTP_REF_NAME }} to ${{ env.BUILDS_TXT }}"
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          push() {
            git reset --hard "${GITHUB_SHA}"
            git pull origin main
            build_sha256=$(shasum -a 256 $TGZ | cut -d ' ' -f 1)
            date=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
            mkdir -p builds/
            touch "${BUILDS_TXT}"
            sed -i.bak "/^${{ env.OTP_REF_NAME }} /d" "${BUILDS_TXT}"
            rm "${BUILDS_TXT}.bak"
            echo -ne "${OTP_REF_NAME} ${OTP_REF} ${date} ${build_sha256}\n$(cat ${BUILDS_TXT})" > "${BUILDS_TXT}"
            sort -u -k1,1 -o "${BUILDS_TXT}" "${BUILDS_TXT}"
            git add builds/
            GIT_AUTHOR_NAME="${{ github.actor }}" \
            GIT_AUTHOR_EMAIL="${{ github.actor }}@users.noreply.github.com" \
            GIT_COMMITTER_NAME="github-actions[bot]" \
            GIT_COMMITTER_EMAIL="github-actions[bot]@users.noreply.github.com" \
              git commit -m "Add ${{ env.OTP_REF_NAME }} to ${{ env.BUILDS_TXT }}"
            git push origin main
          }

          url="https://github.com/${GITHUB_REPOSITORY}/releases/download/${OTP_REF_NAME}/${TGZ}"
          curl --fail -LO "${url}"

          max_retries=5
          attempt=0
          while [ $attempt -lt $max_retries ]; do
            if push; then
              break
            fi
            attempt=$((attempt + 1))
            echo "Retry $attempt/$max_retries failed. Retrying in 10 seconds..."
            sleep 10
          done

          if [ $attempt -eq $max_retries ]; then
            echo "Reached maximum retries ($max_retries). Exiting."
            exit 1
          fi
